CREATE TABLE
    users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT users_pk PRIMARY KEY,
        NAME TEXT NOT NULL
    );

CREATE VIEW
    current_year (VALUE) AS
SELECT
    LAST_VALUE AS VALUE
FROM
    years_sequence;

CREATE VIEW
    current_user_info (id, NAME) AS
SELECT
    id,
    NAME
FROM
    users
WHERE
    NAME = CURRENT_USER;

CREATE TABLE
    financing_sources (
        id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        NAME TEXT NOT NULL
    );

CREATE TABLE
    expenditure_articles (
        id INTEGER DEFAULT NEXTVAL('expenditure_article_id_seq'::regclass) NOT NULL CONSTRAINT expenditure_article_pkey PRIMARY KEY,
        code TEXT NOT NULL,
        NAME TEXT NOT NULL
    );

CREATE TABLE
    project_categories (
        id INTEGER DEFAULT NEXTVAL('project_category_id_seq'::regclass) NOT NULL CONSTRAINT project_category_pkey PRIMARY KEY,
        NAME TEXT NOT NULL
    );

CREATE TABLE
    payment_methods (
        id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        NAME TEXT NOT NULL
    );

CREATE TABLE
    expenditures (
        YEAR INTEGER DEFAULT 0 NOT NULL,
        number INTEGER DEFAULT 0 NOT NULL,
        registration_date date DEFAULT CURRENT_DATE NOT NULL,
        financing_source_id INTEGER NOT NULL CONSTRAINT expenditures_financing_sources_id_fk REFERENCES financing_sources,
        expenditure_article_id INTEGER NOT NULL CONSTRAINT expenditures_expenditure_articles_id_fk REFERENCES expenditure_articles,
        project_category_id INTEGER CONSTRAINT expenditures_project_categories_id_fk REFERENCES project_categories,
        details TEXT NOT NULL,
        procurement_type TEXT NOT NULL,
        ordinance_number TEXT NOT NULL,
        ordinance_date date NOT NULL,
        VALUE NUMERIC(15, 2) NOT NULL,
        payment_method_id INTEGER NOT NULL,
        beneficiary TEXT NOT NULL,
        invoice TEXT,
        noncompliance TEXT,
        remarks TEXT,
        created_by_user_id INTEGER DEFAULT 0 NOT NULL CONSTRAINT expenditures_users_id_fk REFERENCES users,
        CONSTRAINT expenditures_pk PRIMARY KEY (YEAR, number),
        CONSTRAINT check_project_category CHECK (
            check_project_category (financing_source_id, project_category_id)
        )
    );

CREATE TABLE
    commitments (
        YEAR INTEGER DEFAULT 0 NOT NULL,
        number INTEGER DEFAULT 0 NOT NULL,
        registration_date date DEFAULT CURRENT_DATE NOT NULL,
        document_number TEXT,
        validity TEXT,
        financing_source_id INTEGER NOT NULL CONSTRAINT commitments_financing_sources_id_fk REFERENCES financing_sources,
        project_category_id INTEGER CONSTRAINT commitments_project_categories_id_fk REFERENCES project_categories,
        expenditure_article_id INTEGER NOT NULL CONSTRAINT commitments_expenditure_articles_id_fk REFERENCES expenditure_articles,
        partner TEXT,
        VALUE NUMERIC(15, 2),
        procurement_type TEXT,
        remarks TEXT,
        created_by_user_id INTEGER NOT NULL CONSTRAINT commitments_users_id_fk REFERENCES users,
        noncompliance TEXT,
        CONSTRAINT commitments_pk PRIMARY KEY (YEAR, number),
        CONSTRAINT check_project_category CHECK (
            check_project_category (financing_source_id, project_category_id)
        )
    );

CREATE SCHEMA audit;

CREATE TABLE
    audit.tables (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT tables_pk PRIMARY KEY,
        NAME TEXT NOT NULL,
        user_friendly_name TEXT NOT NULL
    );

ALTER TABLE audit.tables OWNER TO ADMIN;

CREATE UNIQUE INDEX tables_name_uindex ON audit.tables (NAME);

GRANT
SELECT
    ON audit.tables TO employee;

CREATE TABLE
    audit.actions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT actions_pk PRIMARY KEY,
        NAME TEXT NOT NULL,
        user_friendly_name TEXT NOT NULL
    );

ALTER TABLE audit.actions OWNER TO ADMIN;

CREATE UNIQUE INDEX actions_name_uindex ON audit.actions (NAME);

GRANT
SELECT
    ON audit.actions TO employee;

CREATE TABLE
    audit.activity_log (
        id INTEGER GENERATED ALWAYS AS IDENTITY CONSTRAINT activity_log_pk PRIMARY KEY,
        TIMESTAMP TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
        user_id INTEGER NOT NULL CONSTRAINT activity_log_users_id_fk REFERENCES public.users,
        action_id INTEGER NOT NULL CONSTRAINT activity_log_actions_id_fk REFERENCES audit.actions,
        target_table_id INTEGER NOT NULL CONSTRAINT activity_log_tables_id_fk REFERENCES audit.tables,
        target_object_id TEXT NOT NULL
    );

ALTER TABLE audit.activity_log OWNER TO ADMIN;

GRANT INSERT,
SELECT
    ON audit.activity_log TO employee;
