CREATE TABLE
    users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT users_pk PRIMARY KEY,
        NAME TEXT NOT NULL
    );

CREATE TABLE
    financing_sources (
        id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        NAME TEXT NOT NULL
    );

CREATE TABLE
    expenditure_articles (
        id INTEGER DEFAULT NEXTVAL('expenditure_article_id_seq'::regclass) NOT NULL CONSTRAINT expenditure_article_pkey PRIMARY KEY,
        code TEXT NOT NULL,
        NAME TEXT NOT NULL
    );

CREATE TABLE
    project_categories (
        id INTEGER DEFAULT NEXTVAL('project_category_id_seq'::regclass) NOT NULL CONSTRAINT project_category_pkey PRIMARY KEY,
        NAME TEXT NOT NULL
    );

CREATE TABLE
    payment_methods (
        id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        NAME TEXT NOT NULL
    );

CREATE TABLE
    expenditures (
        YEAR INTEGER DEFAULT 0 NOT NULL,
        number INTEGER DEFAULT 0 NOT NULL,
        registration_date date DEFAULT CURRENT_DATE NOT NULL,
        financing_source_id INTEGER NOT NULL CONSTRAINT expenditures_financing_sources_id_fk REFERENCES financing_sources,
        expenditure_article_id INTEGER NOT NULL CONSTRAINT expenditures_expenditure_articles_id_fk REFERENCES expenditure_articles,
        project_category_id INTEGER CONSTRAINT expenditures_project_categories_id_fk REFERENCES project_categories,
        details TEXT NOT NULL,
        expenditure_type TEXT NOT NULL,
        ordinance_number TEXT NOT NULL,
        ordinance_date date NOT NULL,
        VALUE NUMERIC(15, 2) NOT NULL,
        payment_method_id INTEGER NOT NULL,
        beneficiary TEXT NOT NULL,
        invoice TEXT,
        noncompliance TEXT,
        remarks TEXT,
        created_by_user_id INTEGER DEFAULT 0 NOT NULL CONSTRAINT expenditures_users_id_fk REFERENCES users,
        CONSTRAINT expenditures_pk PRIMARY KEY (YEAR, number),
        CONSTRAINT check_project_category CHECK (
            check_project_category (financing_source_id, project_category_id)
        )
    );
